import arcade

SPRITE_SCALING = 1
TILE_SCALING = 1
PLAYER_SCALING = 1

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "bdude"

# Physics
MOVEMENT_SPEED = 5
GRAVITY = 0


CAMERA_SPEED = 0.1
PLAYER_MOVEMENT_SPEED = 4

MINIMAP_BACKGROUND_COLOR = arcade.color.ALMOND


PARTICLE_GRAVITY = 0.05
PARTICLE_FADE_RATE = 3
PARTICLE_MIN_SPEED = 2.5
PARTICLE_SPEED_RANGE = 2.5

PARTICLE_COUNT = 20
PARTICLE_RADIUS = 3
PARTICLE_COLORS = [arcade.color.ALIZARIN_CRIMSON, arcade.color.COQUELICOT, arcade.color.LAVA, arcade.color.KU_CRIMSON, arcade.color.DARK_TANGERINE]
PARTICLE_SPARKLE_CHANCE = 0.02

BOMBTIMEOUT = 2000
BOMBTICKER = 10

FLAME_TIME = 1000
FLAME_RATE = 33
FLAME_SPEED = 3
FLAMEX = 16
FLAMEY = 16
PKTHEADER = 64
PKTLEN = 1024*2
FORMAT = 'utf8'

GRIDSIZE = 20
BLOCK = 32

GRAPH_WIDTH = 200
GRAPH_HEIGHT = 120
GRAPH_MARGIN = 5
